version: '3'

services:
  applicationdb:
    image: postgres
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_DB=applicationdb
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=application
    volumes:
      - ./applicationdb:/var/lib/postgresql/data

  rabbitmq:
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5632:5672
      - 8093:15672
    environment:
      - RABBITMQ_DEFAULT_USER=application
      - RABBITMQ_DEFAULT_PASS=application
